export const postList = [
  { text: "¡Hoy es un gran día!", images: [], user: null, likes: [] },
  { text: "Disfrutando del sol en la playa.", images: [], user: null, likes: [] },
  { text: "Nuevo libro en mi estantería.", images: [], user: null, likes: [] },
  { text: "¡Qué hermoso atardecer!", images: [], user: null, likes: [] },
  { text: "Día de picnic en el parque.", images: [], user: null, likes: [] },
  { text: "Explorando nuevas rutas de senderismo.", images: [], user: null, likes: [] },
  { text: "Preparando una deliciosa cena.", images: [], user: null, likes: [] },
  { text: "Un día en el campo con amigos.", images: [], user: null, likes: [] },
  { text: "Empezando el día con una taza de café.", images: [], user: null, likes: [] },
  { text: "Celebrando mi cumpleaños.", images: [], user: null, likes: [] },
  { text: "Viendo mi serie favorita.", images: [], user: null, likes: [] },
  { text: "Descubriendo nuevas recetas de cocina.", images: [], user: null, likes: [] },
  { text: "Listo para empezar un nuevo proyecto.", images: [], user: null, likes: [] },
  { text: "Practicando yoga en el jardín.", images: [], user: null, likes: [] },
  { text: "Pintando un cuadro al aire libre.", images: [], user: null, likes: [] },
  { text: "Recorriendo la ciudad en bicicleta.", images: [], user: null, likes: [] },
  { text: "No hay nada como un baño relajante.", images: [], user: null, likes: [] },
  { text: "Disfrutando de un concierto en vivo.", images: [], user: null, likes: [] },
  { text: "Domingo de barbacoa en familia.", images: [], user: null, likes: [] },
  { text: "Un día perfecto para leer en el jardín.", images: [], user: null, likes: [] },
  { text: "Viajando a un lugar desconocido.", images: [], user: null, likes: [] },
  { text: "Haciendo ejercicio al aire libre.", images: [], user: null, likes: [] },
  { text: "Una noche de juegos de mesa.", images: [], user: null, likes: [] },
  { text: "Preparando un delicioso desayuno.", images: [], user: null, likes: [] },
  { text: "Día de spa para relajarse.", images: [], user: null, likes: [] },
  { text: "Descubriendo nuevas tendencias de moda.", images: [], user: null, likes: [] },
  { text: "Una tarde de fotografía en la naturaleza.", images: [], user: null, likes: [] },
  { text: "Disfrutando de un concierto al aire libre.", images: [], user: null, likes: [] },
  { text: "Listo para un día de compras.", images: [], user: null, likes: [] },
  { text: "Recorriendo la ciudad en patineta.", images: [], user: null, likes: [] },
];
